name: Deploy the application to production

env:
  #  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  install-processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: inspect the aws dir
        run: ls -la $HOME/.aws

      - name: test the AWS CLI
        run: aws --version && aws ec2 describe-instances


