name: Deploy the application to production

env:
  #  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  install-processor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: configure AWS
#        run: python3 --version &&  python3 config_aws.py $HOME/.aws

#      - name: inspect the aws dir
#        run: ls -la $HOME/.aws

      - name: test the AWS CLI
        run: aws --version && aws ec2 describe-instances


# - name: AWS: Deploy to ECR
#   uses: Terranovax/aws-ecr-deploy@v1
#   with:
#     # The AWS account id
#     account_id: 
#     # The AWS access key id
#     access_key_id: 
#     # The AWS secret access key
#     secret_access_key: 
#     # The AWS region of the ECR repo
#     region: 
#     # Create the AWS ECR repo if it doesn't exist
#     create_repo: # optional
#     # Path to Dockerfile to build an image for deploying to ECR
#     dockerfile: # optional, default is ./Dockerfile
#     # Additional build arguments to pass into Docker build
#     docker_build_args: # optional
#     # Path to Dockerfile, defaults to working directory
#     path: # optional, default is .
#     # Name of your ECR repository. Defaults to the Github repo name in the lowercase format: {owner}/{repo_name}
#     repo: # optional
#     # Comma-separated string of ECR image tags to apply
#     tags: # optional, default is latest
