name: Deploy the application to production

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PODCAST_RMQ_ADDRESS: ${{ secrets.PODCAST_RMQ_ADDRESS }}

#  AMI_ID: ami-06fcc1f0bc2c8943f
#  KEYPAIR: bootiful-podcast_processor_05-02-2020
#  SECURITY_GROUP: web-host
#  INSTANCE_TYPE: t2.large
#  VPC_ID: vpc-0accf75a6ca3a1a45
#  SUBNET_ID: subnet-094fab188362e9346
#  INSTANCE_TYPE: t1.micro

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  install-processor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: test the AWS CLI
        run: aws --version && aws ec2 describe-instances

      - name: inspect
        run: cd $GITHUB_WORKSPACE && pwd  && find . && env

      - name: run deploy.sh
        run: cd $GITHUB_WORKSPACE/.github/workflows && ./deploy.sh
